---
name: jsonnet
on:
  pull_request:
    branches: [main]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - uses: aquaproj/aqua-installer@61e2563dfe7674cbf74fe6ec212e444198a3bb00 # v2.0.2
        with:
          aqua_version: v1.30.1
      - run: jsonnet --version
      - run: |
          bash scripts/generate.sh
          git add .
          if ! git diff --cached --exit-code; then
            echo "Please run 'bash scripts/generate.sh'" >&2
            echo "::error title=Please run 'bash scripts/generate.sh'::"
            exit 1
          fi
