name: Validate installer-script.json

on:
  pull_request:
    branches:
      - main
    paths:
      - installer-script.json
      - .github/workflows/renovate-installer-script.yaml
  push:
    branches:
      - main
    paths:
      - installer-script.json
      - .github/workflows/renovate-installer-script.yaml
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@7ab3d8f19305664925f3e626580f075f14e40386 # v0.1.2
        with:
          config_file_path: installer-script.json
